name: Go SDK Test

on:
  push:
    paths:
      - 'clients/go/**'
      - '.github/workflows/go-test.yml'
  pull_request:
    paths:
      - 'clients/go/**'
      - '.github/workflows/go-test.yml'

jobs:
  test-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run tests
        run: |
          cd clients/go
          go test ./...
